ninety_nine_cats/config/routes.rb
Rails.application.routes.draw do
  resources :cats
  resources :cat_rental_request
end

ninety_nine_cats/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ninety_nine_cats/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint(8)        not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)        not null
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Cat < ApplicationRecord
    COLORS = ['Black', 'Yellow', 'Gray', 'White']
    validates :sex, inclusion: {in: ['M', 'F']}
    validates :birth_date, :color, :name, :sex, presence: true

    has_many :cat_rental_requests,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :CatRentalRequest,
        dependent: :destroy

end

ninety_nine_cats/app/models/cat_rental_request.rb
# == Schema Information
#
# Table name: cat_rental_requests
#
#  id         :bigint(8)        not null, primary key
#  cat_id     :integer          not null
#  start_date :date             not null
#  end_date   :date             not null
#  status     :string           default("PENDING"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class CatRentalRequest < ApplicationRecord
    validates :status, presence: true, inclusion: {in: ["PENDING", "APPROVED", "DENIED"]}
    validates :cat_id, :start_date, :end_date, presence: true

    belongs_to :cat,
        primary_key: :id,
        foreign_key: :cat_id,
        class_name: :Cat
    
    def overlapping_requests
        overlapping = CatRentalRequest.select(*).where(self.start_date <= :end_date)
    end
end

ninety_nine_cats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ninety_nine_cats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

    def new
        render :new
    end

    def create
        @cat_rental_request = CatRentalRequest.new(crr_params)

        if @cat_rental_request.save
            redirect_to 
    end

    private
    
    def crr_params 
        params.require(:cat_rental_request).permit(:cat_id, :start_date, :end_date, :status)
    end
end

ninety_nine_cats/app/controllers/cats_controller.rb
class CatsController < ApplicationController

    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        render :new
    end

    def edit
        @cat = Cat.find(params[:id])
        render :edit
    end

    def create
        cat = Cat.new(cat_params)

        if cat.save
            redirect_to cat_url(cat)
        else
            render json: cat.errors.full_messages
        end
    end

    def update
        cat = Cat.find(params[:id])

        if cat.update(cat_params)
            redirect_to cat_url(cat)
        else
            render json: cat.errors.full_messages
        end
    end

    private

    def cat_params
        params.require(:cat).permit(:name, :sex, :color, :birth_date, :description)
    end

end

ninety_nine_cats/app/helpers/application_helper.rb
module ApplicationHelper
end

ninety_nine_cats/app/views/cats/_form.html.erb
<% action_url = (type == :edit ? cat_url(cat) : cats_url)%>

<form action="<%= action_url%>" method='post'>
    <% if type == :edit %>
        <input type='hidden' name="_method" value='patch'>
    <% end %>

    <label>Name
        <input type='text' name='cat[name]' value='<%= cat ? cat.name : ""%>'>
    </label>
    <br>
    <br>

    <label>Sex

        <% if cat.nil? %>
            <input type="radio" name="cat[sex]" value="M"> Male
            <input type="radio" name="cat[sex]" value="F"> Female
        <% elsif cat.sex == 'M' %>
            <input type="radio" name="cat[sex]" value="M" checked> Male
            <input type="radio" name="cat[sex]" value="F"> Female
        <% else %>
            <input type="radio" name="cat[sex]" value="M"> Male
            <input type="radio" name="cat[sex]" value="F" checked> Female
        <% end %>
    </label>
    <br>
    <br>
    
    <label>Color
        <select name = "cat[color]">
            <% if cat.nil? %>
                <option value='' selected> --Select a color-- </option>
            <% end %>

            <% Cat::COLORS.each do |color| %>
                <% if cat && color == cat.color %>
                    <option value='<%= color %>' selected> <%= color %> </option>
                <% else %>
                    <option value='<%= color %>'> <%= color %> </option>
                <% end %>
            <% end %>
        </select>
    </label>
    <br>
    <br>

    <label>Date
        <% if cat.nil? %>
            <input type='date' name='cat[birth_date]'>
        <% else %>
            <input type='date' value="<%= cat.birth_date %>" name='cat[birth_date]'>
        <% end %>
    </label>
    <br>
    <br>

    <label>Description
        <% if cat.nil? %>
            <textarea name='cat[description]' ></textarea>
        <% else %>
            <textarea name='cat[description]' > <%= cat.description %> </textarea>
        <% end %>
    </label>
    <br>
    <br>

    <input type='submit' value='<%= type == :edit ? "Change Cat" : "Create Cat" %>'>

</form>

ninety_nine_cats/app/views/cats/edit.html.erb
<%= render 'form', cat: @cat, type: :edit %>

ninety_nine_cats/app/views/cats/index.html.erb
<ul>
    <% @cats.each do |cat| %>
        <li>
            <%= cat.name %>
        </li>
        <a href='<%=cat_url(cat) %>'>Show me this cat</a>
    <% end %>


</ul>

ninety_nine_cats/app/views/cats/new.html.erb
<%= render 'form', cat: @cat, type: :new %>

ninety_nine_cats/app/views/cats/show.html.erb
<h1> </h1>

<ul>
    <li>name: <%= @cat.name%></li>
    <li>birthdate: <%= @cat.birth_date%></li>
    <li>color: <%= @cat.color%></li>
    <li>sex: <%= @cat.sex%></li>
</ul>

ninety_nine_cats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>